version: "3.8"
services:
  backend:
    build: ./Backend
    container_name: backend
    ports:
      -"8000:8000"
  
  frontend:
    build: ./frontend
    container_name: primeros-auxilios-prevencion
    ports:
      -"8080:80"

    depends_on:
      - backend